# Computing probabilities of placings in a competition

<p>Consider a competition with 3 participants, and assume we know the probabilities of winning for each partitipant, e.g. 50%, 30% and 20% for the participants 1, 2, and 3 respectively. This means that we expect that 50% of the time participant 1 would win the competition, 30% of the time participant 2 would win the competition, and the rest 20% of the time the winner would be participant 3. What about places of other participants when the first one wins? I.e., can we calculate the probabilities of placements (1,2,3) and (1,3,2)?</p>

<p>Just knowing probabilities of winning in not sufficient to solve the problem. However if we assume that probabilities of winning reflect <i>relative strength</i> of participants, the situation changes. By relative strength we mean the proportion 5:3:2 in which the participants win the competitions, and assume that the proportions kept untouched in a competition with a subset of participants. E.g., in a competition between participants 2 and 3 the probabilities of winning would form a proportion 30%:20% = 3:2, so in 60% of competitions which were won by number 1, the placing would be (1,2,3), and in the rest 40% of those competitions the placing would be (1,3,2).</p>

<p>With this assumption we would compute probabilities of all placings using recursive tree procedure</p>

## Formal problem statement

<p>Let there be $n$ participants in a competition, denote the set of participants $N=\{1,2,\dots,n\}$, and let $p_k,\,k\in N$ be the probabilities of winning a competition by a participant $k$. We would assume that the probabilities reflect relative strength of participants, that is, in each competition with a nonempty subset of participants $S\subseteq N$ probabilities of winning the competition would keep relative value<p/><br>
$$
p_k^S=\frac{p_k}{\sum_{i\in S}p_i},\;\;k\in S.
$$
<p>In the introductory example we have $n=3$, $N=\{1,2,3\}$, $p_1=0.5$, $p_2=0.3$, $p_3=0.2$, so for $S=\{2,3\}$ we have $p_1^S=0.6$, $p_2^S=0.4$, and for $S=\{1,2\}$ the probabilities are $p_1^S=5/8=0.625$, $p_2^S=3/8=0.375$.</p>

<p>Next denote $R(S)=(i_1,\dots,i_{|S|})$ a permutation of elements of a set $S$; here $|S|$ stands for number of elements of $S$. Any such permutation represents a placement of participants in a competition among members of $S$. With assumptions described, probability of such placement is computed via</p><br>
$$
P(R(S))=p_{i_1}^S P(R(S\setminus\{i_1\}))
$$
<p>which may be contunued recursively as</p><br>
$$
P(R(S)) = p_{i_1}^S p_{i_2}^{S\setminus\{i_1\}} p_{i_3}^{S\setminus\{i_1,i_2\}}\cdots p_{i_{|S|-1}}^{\{i_{|S|-1},i_{|S|}\}} p_{i_{|S|}}^{\{i_{|S|}\}},
$$
<p>where clearly $p_{i_{|S|}}^{\{i_{|S|}\}}=1$, because in a competition with one participant that participant wins with probability 1.

## Code for recursive calculation of a placement probability

In [1]:
# import standard package
import numpy as np

# computing placement probability
def placement_prob(placement, probs_win):
    """ takes a placement, e.g. [2,1,3,0], and probabilities of winning,
    returns the probability of the placement
    """
    n = len(probs_win)
    if n <= 1:
        return 1
    else:
        # pw = probs_win[placement]
        pn = np.delete(probs_win, 0)
        pn = pn / pn.sum()
        pr0 = probs_win[0]
        plc = np.delete(placement, 0)
        return pr0 * placement_prob(plc, pn)

# creating a list of all permutations (placements) of the array a
def permutations(a):
    """ returns a list of all permutations of elements of the array a
    each element of the output list is a permutatation represented by a numpy array

    """
    ls = list()
    n = len(a)
    if n <= 1:
        ls.append(a)
    else:
        for i in range(n):
            tmp = a[i]
            aa = np.delete(a, i)
            lss = permutations(aa)
            lss = [np.concatenate(([tmp], x)) for x in lss]
            ls.extend(lss)
    return ls

## Examples

### Generic code

In [2]:
def example(probs_win):
    """ takes an array of winning probabilities,
    computes probabilities for all placements,
    and prints them out
    """
    participants = np.array(range(len(probs_win)))
    all_placements = permutations(participants)

    # compute probabilities of all permutations
    probs = np.array([placement_prob(plc, probs_win[plc]) for plc in all_placements])

    # print out probabilities
    for i in range(len(probs)):
        print(all_placements[i] + 1, probs[i])

    # check that probabilities sum to 1
    print('number of placements: {0}, sum of probabilities: {1}'.format(len(probs), probs.sum()))

### Two participants

In [3]:
probs_win = np.array([0.6, 0.4])
example(probs_win)

[1 2] 0.6
[2 1] 0.4
number of placements: 2, sum of probabilities: 1.0


### Three participants

In [4]:
probs_win = np.array([0.5,0.3,0.2])
example(probs_win)

[1 2 3] 0.3
[1 3 2] 0.2
[2 1 3] 0.214285714286
[2 3 1] 0.0857142857143
[3 1 2] 0.125
[3 2 1] 0.075
number of placements: 6, sum of probabilities: 1.0


### Four participants

In [5]:
probs_win = np.array([0.4, 0.3, 0.2, 0.1])
example(probs_win)

[1 2 3 4] 0.133333333333
[1 2 4 3] 0.0666666666667
[1 3 2 4] 0.1
[1 3 4 2] 0.0333333333333
[1 4 2 3] 0.04
[1 4 3 2] 0.0266666666667
[2 1 3 4] 0.114285714286
[2 1 4 3] 0.0571428571429
[2 3 1 4] 0.0685714285714
[2 3 4 1] 0.0171428571429
[2 4 1 3] 0.0285714285714
[2 4 3 1] 0.0142857142857
[3 1 2 4] 0.075
[3 1 4 2] 0.025
[3 2 1 4] 0.06
[3 2 4 1] 0.015
[3 4 1 2] 0.0142857142857
[3 4 2 1] 0.0107142857143
[4 1 2 3] 0.0266666666667
[4 1 3 2] 0.0177777777778
[4 2 1 3] 0.0222222222222
[4 2 3 1] 0.0111111111111
[4 3 1 2] 0.0126984126984
[4 3 2 1] 0.00952380952381
number of placements: 24, sum of probabilities: 1.0


### Four participants, different probabilities

In [6]:
probs_win = np.array([0.3, 0.5, 0.1, 0.1])
example(probs_win)

[1 2 3 4] 0.107142857143
[1 2 4 3] 0.107142857143
[1 3 2 4] 0.0357142857143
[1 3 4 2] 0.00714285714286
[1 4 2 3] 0.0357142857143
[1 4 3 2] 0.00714285714286
[2 1 3 4] 0.15
[2 1 4 3] 0.15
[2 3 1 4] 0.075
[2 3 4 1] 0.025
[2 4 1 3] 0.075
[2 4 3 1] 0.025
[3 1 2 4] 0.0277777777778
[3 1 4 2] 0.00555555555556
[3 2 1 4] 0.0416666666667
[3 2 4 1] 0.0138888888889
[3 4 1 2] 0.00416666666667
[3 4 2 1] 0.00694444444444
[4 1 2 3] 0.0277777777778
[4 1 3 2] 0.00555555555556
[4 2 1 3] 0.0416666666667
[4 2 3 1] 0.0138888888889
[4 3 1 2] 0.00416666666667
[4 3 2 1] 0.00694444444444
number of placements: 24, sum of probabilities: 1.0
